# vim:expandtab
#
swagger: "2.0"
info:
  description: "Web Application Service Demo"
  title: "web-application-service"
  version: "1.0"
host: "frontend.endpoints.[PROJECT].cloud.goog"
x-google-endpoints:
- name: "frontend.endpoints.[PROJECT].cloud.goog"
  target: "[FRONTEND IP]"
basePath: "/"
consumes:
- "application/json"
produces:
- "application/json"
schemes:
- "https"

paths:
  "/debug/health":
    get:
      description: "Health check"
      operationId: "healthcheck"
      responses:
        200:
          description: "Success"
          schema:
            type: string
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorModel"

  "/login":
    post:
      description: "Provide authentication details and get a token"
      operationId: "login"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/loginResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorModel"
      parameters:
        - name: "request"
          in: body
          schema:
            $ref: "#/definitions/loginRequest"

  "/document":
    get:
      description: "Get a list of documents"
      operationId: "list"
      responses:
        200:
          description: "Success"
          schema:
            type: array
            items:
              $ref: "#/definitions/metadataRow"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorModel"
      security:
        - auth0_jwk: []

    post:
      description: "upload a document"
      operationId: "upload"
      parameters:
        - name: "request"
          in: body
          schema:
            $ref: "#/definitions/uploadRequest"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/metadataRow"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorModel"
      security:
        - auth0_jwk: []

  "/document/{id}":
    get:
      description: "Get a document"
      operationId: "get"
      responses:
        200:
          description: "Success"
          schema:
            type: string
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorModel"
      parameters:
        - name: "id"
          in: path
          type: string
      security:
        - auth0_jwk: []

    delete:
      description: "Delete a document"
      operationId: "delete"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/deleteResponse"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/ErrorModel"
      parameters:
        - name: "id"
          in: path
          type: string
      security:
        - auth0_jwk: []


definitions:
  loginRequest:
    properties:
      email:
        type: string
      password:
        type: string
  loginResponse:
    properties:
      token:
        type: string

  listResponse:
    properties:
      id:
        type: string
      name:
        type: string
      mime_type:
        type: string

  uploadRequest:
    properties:
      name:
        type: string
      body:
        type: string
      mime_type:
        type: string

  deleteResponse:
    properties:
      status:
        type: string

  metadataRow:
    properties:
      id:
        type: string
      name:
        type: string
      uploaded:
        type: string
        format: date-time
      mime_type:
        type: string
      size:
        type: integer

  ErrorModel:
    type: object
    required:
      - message
      - code
    properties:
      message:
        type: string
      code:
        type: integer
        minimum: 100
        maximum: 600


securityDefinitions:
  auth0_jwk:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://web-application-demo.auth0.com/"
    x-google-jwks_uri: "https://web-application-demo.auth0.com/.well-known/jwks.json"
    x-google-audiences: "9pCzl0POsoRl7JWcBJ9013OBGw3aNUIL"
