# vim:sw=2 expandtab

steps:
  - name: 'golang:1.9'
    args: ['bash', './cloudbuild.sh']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend', '.']
images: ['gcr.io/$PROJECT_ID/frontend']
