# vim:sw=2 expandtab

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  # Keep a history of 10 updates
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: frontend
        track: canary
    spec:
      serviceAccountName: frontend
      containers:
        - name: frontend
          image: gcr.io/[PROJECT]/frontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          args: ["--config", "/etc/was/config.json"]
          env:
            - name: PORT
              value: "80"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/service-key/key.json"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /debug/health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /debug/health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: service-key
              mountPath: "/etc/service-key"
              readOnly: true
            - name: config
              mountPath: "/etc/was"
              readOnly: true
            - name: podinfo
              mountPath: "/etc/podinfo"
              readOnly: false
          resources:
            limits:
              cpu: 1
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 100Mi
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:1
          args: [
            "--http_port", "8080",
            "--ssl_port", "443",
            "--backend", "127.0.0.1:80",
            "--service", "frontend.endpoints.[PROJECT].cloud.goog",
            "--version", "2018-02-13r10",
            "--service_account_key", "/etc/nginx/creds/esp-key.json",
          ]
          ports:
            - containerPort: 443
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/nginx/creds
              name: esp-key
              readOnly: true
            - mountPath: /etc/nginx/ssl
              name: ssl-certs
              readOnly: true
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 200m
              memory: 100Mi
      volumes:
        - name: service-key
          secret:
            secretName: frontend-key
        - name: config
          configMap:
            name: config
        - name: esp-key
          secret:
            secretName: esp-key
        - name: ssl-certs
          secret:
            secretName: nginx-ssl
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                containerName: frontend
                fieldRef:
                  fieldPath: metadata.labels


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  # Keep a history of 10 updates
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: frontend
        track: stable
    spec:
      serviceAccountName: frontend
      containers:
        - name: frontend
          image: gcr.io/[PROJECT]/frontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          args: ["--config", "/etc/was/config.json"]
          env:
            - name: PORT
              value: "80"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/service-key/key.json"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /debug/health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /debug/health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: service-key
              mountPath: "/etc/service-key"
              readOnly: true
            - name: config
              mountPath: "/etc/was"
              readOnly: true
            - name: podinfo
              mountPath: "/etc/podinfo"
              readOnly: false
          resources:
            limits:
              cpu: 1
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 100Mi
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:1
          args: [
            "--http_port", "8080",
            "--ssl_port", "443",
            "--backend", "127.0.0.1:80",
            "--service", "frontend.endpoints.[PROJECT].cloud.goog",
            "--version", "2018-02-13r10",
            "--service_account_key", "/etc/nginx/creds/esp-key.json",
          ]
          ports:
            - containerPort: 443
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/nginx/creds
              name: esp-key
              readOnly: true
            - mountPath: /etc/nginx/ssl
              name: ssl-certs
              readOnly: true
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 200m
              memory: 100Mi
      volumes:
        - name: service-key
          secret:
            secretName: frontend-key
        - name: config
          configMap:
            name: config
        - name: esp-key
          secret:
            secretName: esp-key
        - name: ssl-certs
          secret:
            secretName: nginx-ssl
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                containerName: frontend
                fieldRef:
                  fieldPath: metadata.labels

